install:
  - dir

environment:
    matrix:  
    # first group
    - target: Debug

    # second group
    - target: Release

platform:
    - Any CPU

configuration:
    - Debug
    - Release

matrix:
    fast_finish: true
  
build:
  project: C:/projects/ccm/CCM.sln
  verbosity: minimal
