@ECHO OFF

SET BINPATH=%~dp0

REM 
REM VS 2008
REM

SET VS2008_ROOT_XP="%USERPROFILE%\My Documents\Visual Studio 2008"
SET VS2008_ROOT_VISTA="%USERPROFILE%\Documents\Visual Studio 2008"

IF EXIST %VS2008_ROOT_XP% (
  XCOPY "%BINPATH%CCMEngine.dll" %VS2008_ROOT_XP%\Addins\ /Y /Q 2>NUL
  XCOPY "%BINPATH%vsCCM.dll" %VS2008_ROOT_XP%\Addins\ /Y /Q 2>NUL
  XCOPY "%BINPATH%vsCCM_2008.AddIn" %VS2008_ROOT_XP%\Addins\ /Y /Q 2>NUL
  XCOPY "%BINPATH%ccm.config" %VS2008_ROOT_XP%\Addins\ /Y /Q 2>NUL
)

IF EXIST %VS2008_ROOT_VISTA% (
  XCOPY "%BINPATH%CCMEngine.dll" %VS2008_ROOT_VISTA%\Addins\ /Y /Q 2>NUL
  XCOPY "%BINPATH%vsCCM.dll" %VS2008_ROOT_VISTA%\Addins\ /Y /Q 2>NUL
  XCOPY "%BINPATH%vsCCM_2008.AddIn" %VS2008_ROOT_VISTA%\Addins\ /Y /Q 2>NUL
  XCOPY "%BINPATH%ccm.config" %VS2008_ROOT_VISTA%\Addins\ /Y /Q 2>NUL
)

REM 
REM VS 2010
REM

SET VS2010_ROOT_XP="%USERPROFILE%\My Documents\Visual Studio 2010"
SET VS2010_ROOT_VISTA="%USERPROFILE%\Documents\Visual Studio 2010"

IF EXIST %VS2010_ROOT_XP% (
  XCOPY "%BINPATH%CCMEngine.dll" %VS2010_ROOT_XP%\Addins\ /Y /Q 2>NUL
  XCOPY "%BINPATH%vsCCM.dll" %VS2010_ROOT_XP%\Addins\ /Y /Q 2>NUL
  XCOPY "%BINPATH%vsCCM_2010.AddIn" %VS2010_ROOT_XP%\Addins\ /Y /Q 2>NUL
  XCOPY "%BINPATH%ccm.config" %VS2010_ROOT_XP%\Addins\ /Y /Q 2>NUL
)

IF EXIST %VS2010_ROOT_VISTA% (
  XCOPY "%BINPATH%CCMEngine.dll" %VS2010_ROOT_VISTA%\Addins\ /Y /Q 2>NUL
  XCOPY "%BINPATH%vsCCM.dll" %VS2010_ROOT_VISTA%\Addins\ /Y /Q 2>NUL
  XCOPY "%BINPATH%vsCCM_2010.AddIn" %VS2010_ROOT_VISTA%\Addins\ /Y /Q 2>NUL
  XCOPY "%BINPATH%ccm.config" %VS2010_ROOT_VISTA%\Addins\ /Y /Q 2>NUL
)

REM 
REM VS 2012
REM

SET VS2012_ROOT_XP="%USERPROFILE%\My Documents\Visual Studio 2012"
SET VS2012_ROOT_VISTA="%USERPROFILE%\Documents\Visual Studio 2012"

IF EXIST %VS2012_ROOT_XP% (
  XCOPY "%BINPATH%CCMEngine.dll" %VS2012_ROOT_XP%\Addins\ /Y /Q 2>NUL
  XCOPY "%BINPATH%vsCCM.dll" %VS2012_ROOT_XP%\Addins\ /Y /Q 2>NUL
  XCOPY "%BINPATH%vsCCM_2012.AddIn" %VS2012_ROOT_XP%\Addins\ /Y /Q 2>NUL
  XCOPY "%BINPATH%ccm.config" %VS2012_ROOT_XP%\Addins\ /Y /Q 2>NUL
)

IF EXIST %VS2012_ROOT_VISTA% (
  XCOPY "%BINPATH%CCMEngine.dll" %VS2012_ROOT_VISTA%\Addins\ /Y /Q 2>NUL
  XCOPY "%BINPATH%vsCCM.dll" %VS2012_ROOT_VISTA%\Addins\ /Y /Q 2>NUL
  XCOPY "%BINPATH%vsCCM_2012.AddIn" %VS2012_ROOT_VISTA%\Addins\ /Y /Q 2>NUL
  XCOPY "%BINPATH%ccm.config" %VS2012_ROOT_VISTA%\Addins\ /Y /Q 2>NUL
)

EXIT 0

